name: InferSharp
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  infer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Run Infer#
        uses: microsoft/infersharpaction@b749060de518f410f92c87d37d2366e5e9d7c5fc # v1.5
        id: runinfersharp

      - name: Upload SARIF output to GitHub Security Center
        uses: github/codeql-action/upload-sarif@7188fc363630916deb702c7fdcf4e481b751f97a # v4
        if: success() && hashFiles('infer-out/report.sarif') != ''
        with:
          sarif_file: infer-out/report.sarif
        continue-on-error: true
